name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        uses: docker/setup-qemu-action@v2

      - name: Copy .env.example to .env
        run: cp ./IntegrationTests/.env.example ./IntegrationTests/.env

      - name: Run integration script
        run: cd IntegrationTests && yarn run test:integration
