name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: ./IntegrationTests/docker-compose.yml

      - name: Ensure Docker Compose is available
        run: docker-compose version

      - name: Copy .env.example to .env
        run: cp ./IntegrationTests/.env.example ./IntegrationTests/.env

      - name: Run integration script
        run: cd IntegrationTests && npm run test:integration
